version: "3"
services:

  agent:
    build: ./
    hostname: bamboo-agent
    image: dcagatay/java-node-bamboo-agent:latest
    privileged: true
    volumes:
      - ./data/agent-home:/home/bamboo/bamboo-agent-home
    environment:
      BAMBOO_SERVER_URL: "http://bamboo-server.example.com:8085"
      # SECURITY_TOKEN: "xxx"
    # restart: unless-stopped
